<?php
// This file generated by Propel 1.7.3-dev convert-conf target
// from XML runtime conf file /var/www/gc/p/myproject1/.admin/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'myproject1' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=gc_myproject1;charset=utf8;',
        'user' => 'gc_myproject1',
        'password' => 'njhghqmfyczbwwbmvxymfl',
      ),
    ),
    'default' => 'myproject1',
  ),
  'generator_version' => '1.7.3-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap.php');
return $conf;