<?php

namespace App;


$omMap = [
    [
        'name' => 'Client',
        'desc' => 'Clients',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => [
            'billing',
        ],
        'display' => 'Client',
    ],
    [
        'name' => 'Billing',
        'desc' => 'Billings',
        'parent_table' => 'client',
        'parent_menu' => '',
        'child_table' => [
            'billing_line',
            'cost_line',
            'payment_line',
        ],
        'display' => 'Client - Billing',
    ],
    [
        'name' => 'BillingLine',
        'desc' => 'Entriess',
        'parent_table' => 'billing',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Billing - Entries',
    ],
    [
        'name' => 'PaymentLine',
        'desc' => 'Payment entries',
        'parent_table' => 'billing',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Billing - Payment entry',
    ],
    [
        'name' => 'CostLine',
        'desc' => 'Expenses',
        'parent_table' => 'billing',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Billing - Expense',
    ],
    [
        'name' => 'Project',
        'desc' => 'Projects',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => [
            'billing_line',
            'time_line',
        ],
        'display' => 'Project',
    ],
    [
        'name' => 'TimeLine',
        'desc' => 'Times',
        'parent_table' => 'project',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Project - Time',
    ],
    [
        'name' => 'Supplier',
        'desc' => 'Suppliers',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => [
            'cost_line',
        ],
        'display' => 'Supplier',
    ],
    [
        'name' => 'AuthyGroupX',
        'desc' => 'Groups',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Group',
    ],
    [
        'name' => 'TemplateFile',
        'desc' => 'Files',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'File',
    ],
    [
        'name' => 'MessageI18n',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'MessageI18n',
    ],
    [
        'name' => 'BillingCategory',
        'desc' => 'Category billings',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Category billing',
    ],
    [
        'name' => 'Authy',
        'desc' => 'Users',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'authy_group_x',
            'authy_log',
        ],
        'display' => 'User',
    ],
    [
        'name' => 'Country',
        'desc' => 'Countries',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Country',
    ],
    [
        'name' => 'AuthyGroup',
        'desc' => 'Groups',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Group',
    ],
    [
        'name' => 'AuthyLog',
        'desc' => 'Login logs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Login log',
    ],
    [
        'name' => 'Message',
        'desc' => 'Messages',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Message',
    ],
    [
        'name' => 'Config',
        'desc' => 'Settings',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Setting',
    ],
    [
        'name' => 'ApiRbac',
        'desc' => 'API ACLs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'api_log',
        ],
        'display' => 'API ACL',
    ],
    [
        'name' => 'ApiLog',
        'desc' => 'API logs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'API log',
    ],
    [
        'name' => 'Template',
        'desc' => 'Templates',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'template_file',
        ],
        'display' => 'Template',
    ],
];
