<?php

namespace App;


    return [
    'html' => [
        'GET' => [
            'Client' => [],
            'Billing' => [],
            'BillingLine' => [],
            'PaymentLine' => [],
            'CostLine' => [],
            'Project' => [],
            'TimeLine' => [],
            'Authy' => [],
            'Country' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'POST' => [
            'Client' => [],
            'Billing' => [],
            'BillingLine' => [],
            'PaymentLine' => [],
            'CostLine' => [],
            'Project' => [],
            'TimeLine' => [],
            'Authy' => [],
            'Country' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
    ],
    'json' => [
        'GET' => [
            'Client' => [],
            'Billing' => [],
            'BillingLine' => [],
            'PaymentLine' => [],
            'CostLine' => [],
            'Project' => [],
            'TimeLine' => [],
            'Authy' => [],
            'Country' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'POST' => [
            'Client' => [],
            'Billing' => [],
            'BillingLine' => [],
            'PaymentLine' => [],
            'CostLine' => [],
            'Project' => [],
            'TimeLine' => [],
            'Authy' => [],
            'Country' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'PATCH' => [
            'Client' => [],
            'Billing' => [],
            'BillingLine' => [],
            'PaymentLine' => [],
            'CostLine' => [],
            'Project' => [],
            'TimeLine' => [],
            'Authy' => [],
            'Country' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'DELETE' => [
            'Client' => [],
            'Billing' => [],
            'BillingLine' => [],
            'PaymentLine' => [],
            'CostLine' => [],
            'Project' => [],
            'TimeLine' => [],
            'Authy' => [],
            'Country' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
    ],
];


